### ISSUE TITLE
extract origin dual fisheye and imu measurements

### ISSUE THREAD

**Issue by fushi219** [trek-view/max2sphere#1]
Thanks so much for your job! i'm a newbie about gopro or ffmeg. I wonder  if could i get the origin dual fisheye images and imu measurements from gopro max .360 file as i want to use it to do vio job. Thanks for your help!

**Comment by himynamesdave** [comment]
Thanks @fushi219 .

Check out this post, it might help: https://www.trekview.org/blog/2022/gopro-telemetry-exporter-getting-started/

If not, please raise any other general questions like this one on our Discord: https://discord.gg/ZVk7h9hCfw
